#!/usr/bin/env python3
"""
BoxBox – main generator
Runs all series scrapers and combines output into a single boxbox.ics feed.

To add a new series:
  1. Create scrapers/myseries.py with a get_sessions() function
  2. Import it here and add to SCRAPERS list
"""

import hashlib
from datetime import datetime
from pathlib import Path

from icalendar import Calendar, Event
import pytz

# ── Import series scrapers ──────────────────────────────────────────────────
from scrapers import btcc, f1

SCRAPERS = [
    btcc,
    f1,
]
# ───────────────────────────────────────────────────────────────────────────

UTC = pytz.utc


def build_calendar(all_sessions):
    cal = Calendar()
    cal.add("prodid", "-//BoxBox Motorsport Calendar//boxbox//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("method", "PUBLISH")
    cal.add("x-wr-calname", "BoxBox")
    cal.add("x-wr-timezone", "Europe/London")
    cal.add("x-wr-caldesc", "Motorsport session times. Auto-generated by BoxBox.")
    cal.add("refresh-interval;value=duration", "P1D")
    cal.add("x-published-ttl", "P1D")

    for s in all_sessions:
        event = Event()
        event.add("summary", f"[{s['series']}] {s['title']} \U0001f3c1")
        event.add("dtstart", s["start"])
        event.add("dtend", s["end"])
        event.add("location", s["location"])
        event.add("url", s["url"])
        event.add("description", s["description"])

        uid_src = f"{s['series']}-{s['title']}-{s['start'].isoformat()}"
        event.add("uid", hashlib.md5(uid_src.encode()).hexdigest() + "@boxbox-cal")
        event.add("dtstamp", datetime.now(UTC))
        cal.add_component(event)

    return cal


if __name__ == "__main__":
    print("BoxBox – Motorsport Calendar Generator")
    print("=" * 50)

    all_sessions = []

    for scraper in SCRAPERS:
        name = scraper.__name__.split(".")[-1].upper()
        print(f"\n[{name}]")
        try:
            sessions = scraper.get_sessions()
            all_sessions.extend(sessions)
            print(f"  → {len(sessions)} sessions")
        except Exception as exc:
            print(f"  ERROR: {exc}")

    # Sort chronologically
    all_sessions.sort(key=lambda s: s["start"])

    print(f"\nTotal sessions: {len(all_sessions)}")

    cal = build_calendar(all_sessions)
    out = Path("boxbox.ics")
    out.write_bytes(cal.to_ical())
    print(f"Written: {out}  ({out.stat().st_size:,} bytes)")
